// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilityBillManager.Data;

#nullable disable

namespace UtilityBillManager.Migrations
{
    [DbContext(typeof(BillContext))]
    [Migration("20250411183942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("UtilityBillManager.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("CostUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("Meter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UsageKwh")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
